---
- name: Update package mirrors and existing packages
  apt: update_cache=yes upgrade=yes  

- name: Install required system packages
  apt: name={{ sys_packages }} state=latest

- name: Adds ansible user to www-data group
  user:
    name: ansible
    state: present
    groups: www-data
    append: true     

# Mount the NFS Share for config files
- name: Create Web directory if its missing
  ansible.builtin.file:
    path: /mnt/Web
    state: directory
    mode: '0755'

- name: Mount the Web NFS Share
  ansible.posix.mount:
    src: "{{ hostvars[groups['storage'][0]].ansible_host }}:/mnt/Web"
    path: /mnt/Web
    opts: rw,sync,hard,intr,fsc
    state: mounted
    fstype: nfs    

# Configure Nginx
- name: Remove default Nginx config
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: restart nginx    

- name: Update Nginx config
  template: 
    src=nginx.conf 
    dest=/etc/nginx/nginx.conf 
    backup=no
  notify: restart nginx        

# Configure PHP
- name: Copy PHP config
  become: yes
  become_user: root            
  copy: 
    src: php.ini 
    dest: /etc/php/7.4/fpm/php.ini
    backup: no                      
  notify: restart php-fpm    

- name: Update php-fpm pool config
  become: yes
  become_user: root            
  copy: 
    src: www.conf 
    dest: /etc/php/7.4/fpm/pool.d/www.conf 
    backup: no
  notify: restart php-fpm        

# Configure Disk Cache
- name: Update Cachefilesd defaults file
  become: yes
  become_user: root            
  copy: 
    src: cachefilesd 
    dest: /etc/default/cachefilesd 
    backup: no
  notify: restart cachefilesd        

- name: Update Cachefilesd config file
  become: yes
  become_user: root            
  copy: 
    src: cachefilesd.conf 
    dest: /etc/cachefilesd.conf 
    backup: no
  notify: restart cachefilesd        

- name: Create Cached Web directory if its missing
  become: yes
  become_user: root                    
  ansible.builtin.file:
    path: /mnt/CWeb
    state: directory
    mode: '0755'
  notify: restart cachefilesd        

# Configure Netdata
- name: Add netdata config for Nginx
  become: yes
  become_user: root        
  copy:
    src: netdatanginx.conf
    dest: /etc/netdata/go.d/nginx.conf
    owner: root
    group: root
    mode: u=rx,g=rx,o=r
    backup: no
  notify: restart netdata    

- name: Add netdata config for PHP-FPM
  become: yes
  become_user: root        
  copy:
    src: netdataphpfpm.conf
    dest: /etc/netdata/go.d/phpfpm.conf
    owner: root
    group: root
    mode: u=rx,g=rx,o=r
    backup: no
  notify: restart netdata