---
- name: Install required system packages
  apt: name={{ sys_packages }} state=present

# Add cloudflare origin cert
- name: Add Cloudflare origin certificate to server(s)
  copy:
    src: beneorigin.pem
    dest: /etc/ssl/private/beneorigin.pem
    remote_src: no

- name: Set ownership for certificate
  ansible.builtin.file:
    path: /etc/ssl/private
    recurse: yes
    owner: haproxy
    group: haproxy

# Upload templated haproxy config
- name: Update HAProxy config
  template: 
    src=haproxy.cfg 
    dest=/etc/haproxy/haproxy.cfg 
    backup=no                
  notify: restart haproxy