# Syncs files from File server to digital ocean spaces for
# faster restore and replacement of node
# Using rlcone sync, it will empty DO space if files are missing
---
- hosts: file[0]  
  tasks: 

        - name: Tell Healthchecks.io that we started the playbook
          ansible.builtin.uri:
            url: https://hc-ping.com/a0784da6-4a36-486d-9f6a-2cc68072c0ad/start
            timeout: 10
            force: true        


#Check if files exist on NFS share, if they dont this playbook will wipe directory
        - name: Make sure we have files to backup
          ansible.builtin.stat:
            path: /mnt/Web/data.txt
          register: nfs_share_data

#Run backup using rclone sync. Ignore errors cause some files will fail, its all good, just speeds recovery
        - name: Sync files from cluster to DO Spaces
          become: true
          become_user: root
          shell: sudo rclone sync /mnt/Web/ Spaces:beneit/FileServerBackups --retries 1 --ignore-errors
          when: nfs_share_data.stat.exists == true
          ignore_errors: true
 
        - name: Tell Healthchecks.io that we finished the playbook
          ansible.builtin.uri:
            url: https://hc-ping.com/a0784da6-4a36-486d-9f6a-2cc68072c0ad
            timeout: 10
            force: true        
