---
- hosts: wpadmin[0]
  become: true
  vars:
    wp_sites: "{{ output.files|map(attribute='path')|map('basename')|list }}"

  tasks: 
    - name: Get List of Wordpress Sites
      ansible.builtin.find:
        paths: /mnt/Web/Websites/Wordpress
        recurse: no
        file_type: directory
      register: output

    - name: Update Wordpress Plugins
      ansible.builtin.shell:
        cmd: "sudo -u www-data wp plugin update --all"
        chdir: "/mnt/Web/Websites/Wordpress/{{ item }}/public_html/"
      loop: "{{ wp_sites }}"
      throttle: 1


      


      