---
- hosts: wpadmin[0]
  become: true

  tasks: 
        - name: Get List of Wordpress Sites
          ansible.builtin.find:
            paths: /mnt/Web/Websites/Wordpress
            recurse: no
            file_type: directory
          register: wp_sites


        - name: Create list of directory names
          find:
            paths: /mnt/Web/Websites/Wordpress
            file_type: directory
          register: dir_list

        - name: Set directory names as a list
          set_fact:
            dir_names: "{{ wp_sites.files | map(attribute='path') | list }}"



        - name: Update Wordpress Plugins
          command: "sudo -u www-data /mnt/Web/Websites/Wordpress/{{ item }}/public_html/wp plugin update --all"
          loop: "{{ wp_sites.files | map(attribute='path') | list }}"