---
- hosts: wpadmin[0]
  become: true

  tasks: 
        - name: Get List of Wordpress Sites
          ansible.builtin.find:
            paths: /mnt/Web/Websites/Wordpress
            recurse: no
            file_type: directory
          register: wp_sites

        - name: Update Wordpress Plugins
          command: "sudo -u www-data /mnt/Web/Websites/Wordpress/{{ item }}/public_html/wp plugin update --all"
          loop: "{{ wp_sites }}"