---
- hosts: wpadmin[0]
  become: true
  vars:
    wp_sites: "{{ output.files|map(attribute='path')|map('basename')|list }}"

  tasks: 
    - name: Get List of Wordpress Sites
      ansible.builtin.find:
        paths: /mnt/Web/Websites/Wordpress
        recurse: no
        file_type: directory
      register: output
    - debug:
        var: wp_sites

