---
- hosts: localhost
  tasks: 

- name: Configure and deploy the balance tier fix
  hosts: loadbalancers
  become: true
  vars:
    webnodes: "{{ groups['webservers'] }}"
    wpanodes: "{{ groups['wp_admin'] }}"
  roles:
    - haproxy
