#################################################
# Loadbalancers config
#################################################
---
    - hosts: loadbalancers
      become: true
      vars_files:
        - group_vars/loadbalancers.yml
      vars:
        backends: "{{ groups['webservers'] }}"

      tasks:

    # Install Packages
        - name: Update package mirrors and existing packages
          apt: update_cache=yes upgrade=yes
    
        - name: Install required system packages
          apt: name={{ sys_packages }} state=latest



    # Netdata
    #    - name: Grant Netdata user access to haproxy group
     #     user:
      #      name: netdata
       #     state: present
        #    groups: netdata,haproxy
         #   append: true
      
          
    # Add cloudflare origin cert
        - name: Add Cloudflare origin certificate to server(s)
          copy:
           src: files/Loadbalancers/beneorigin.pem
           dest: /etc/ssl/private/beneorigin.pem
           remote_src: no

        - name: Set ownership for certificate
          ansible.builtin.file:
            path: /etc/ssl/private/beneorigin.pem
            owner: haproxy
            group: haproxy


    # Upload templated haproxy config

        - name: Update HAProxy config
          template: src=templates/haproxy.cfg 
                      dest=/etc/haproxy/haproxy.cfg 
                      backup=no                


        - name: Add netdata config for haproxy
          become: yes
          become_user: root        
          copy:
            src: files/Loadbalancers/haproxy.conf
            dest: /etc/netdata/python.d/haproxy.conf
            owner: root
            group: root
            mode: u=rx,g=rx,o=r
            backup: no


        - name: Add netdata to the haproxy group
          ansible.builtin.user:
            name: netdata
            group: haproxy

    # Cleanup        
        - name: Restart HAProxy and make sure it starts at boot
          ansible.builtin.systemd: 
            name: haproxy
            enabled: yes
            state: restarted