#################################################
# Loadbalancers config
#################################################
---
    - hosts: all
      become: true
      vars_files:
        - group_vars/loadbalancers.yml
      vars:
        backends: "{{ groups['web'] }}"  

    # This shouldnt be needed but if its not here the playbook doesnt run, i have no idea
      tasks:
        - name: Install Prerequisites
          apt: name=aptitude update_cache=yes state=latest force_apt_get=yes
    
    # Install Packages
        - name: Update package mirrors and existing packages
          apt: update_cache=yes upgrade=yes
    
        - name: Install required system packages
          apt: name={{ sys_packages }} state=latest
          
    # Add cloudflare origin cert
        - name: Add Cloudflare origin certificate to server(s)
          copy:
           src: files/Loadbalancers/beneorigin.pem
           dest: /etc/ssl/private/beneorigin.pem
           remote_src: no 

        - name: Update HAProxy config
          template: src=templates/haproxy.cfg 
                      dest=/etc/haproxy/haproxy.cfg 
                      backup=yes                



    # Cleanup        
        - name: Restart HAProxy and make sure it starts at boot
          ansible.builtin.systemd: 
            name: haproxy
            enabled: yes
            state: restarted           