---
- hosts: localhost
  vars_prompt:
    - name: droplet_type
      prompt: "What type of Droplet would you like to create? Choices: web | loadbalancer (Type exactly as seen here)"
      private: no
  tasks: 
  #Have to generate a random number to be used in server name
        - name: Genrate Random Number for Droplet name
          set_fact:
            num: "{{99 | random(start=11) }}"

##### CREATION #####

# WEB SERVER
        - name: Create a new Web Droplet
          community.digitalocean.digital_ocean_droplet:
            state: present
            oauth_token: "{{ lookup('ansible.builtin.env', 'DO_API_TOKEN') }}"
            name: Bene-NYC-Web{{ num }}v
            size: s-1vcpu-1gb-amd
            region: nyc3
            tags: 
              - "web"
              - "bene"
            image: ubuntu-20-04-x64
            project: Bene IT Websites
            wait_timeout: 500
            ssh_keys: [ a6:84:ee:f8:05:03:7d:24:09:d2:68:84:8e:d3:72:49 ]
          when: droplet_type == "web"             
          register: web_droplet_create_temp


 #LOADBALANCER
        - name: Create a new Loadbalancer Droplet
          community.digitalocean.digital_ocean_droplet:
            state: present
            oauth_token: "{{ lookup('ansible.builtin.env', 'DO_API_TOKEN') }}"
            name: Bene-NYC-LB{{ num }}v
            size: s-1vcpu-1gb-amd
            region: nyc3
            tags: 
              - "loadbalancers"
              - "bene"
            image: ubuntu-20-04-x64
            project: Bene IT Websites
            wait_timeout: 500
            ssh_keys: [ a6:84:ee:f8:05:03:7d:24:09:d2:68:84:8e:d3:72:49 ]
          when: droplet_type == "loadbalancer"   
          register: lb_droplet_create_temp

# Droplet Creation commnad does not pass IP addresses, using seperate task to grab IP address

# WEB SERVER
        - name: Get Private IP address of new Web Droplet
          community.digitalocean.digital_ocean_droplet_info:
            oauth_token: "{{ lookup('ansible.builtin.env', 'DO_API_TOKEN') }}"
            id: "{{ web_droplet_create_temp.data.droplet.id }}"
          register: web_droplet_temp
          when: droplet_type == "web"


        - name: Add the new Web Droplet to the inventory file
          become: true
          ansible.builtin.lineinfile:
            path=/etc/ansible/hosts
            state=present
            insertafter="\[webservers\]"
            line="{{ web_droplet_temp.data[0].name }} ansible_host={{ (web_droplet_temp.data[0].networks.v4[1].ip_address) }}"
          when: droplet_type == "web" 

        - name: Add the new Web Droplet to the inventory file again for provisioning
          become: true
          ansible.builtin.lineinfile:
            path=/etc/ansible/hosts
            state=present
            insertafter="\[provisioning\]"
            line="{{ web_droplet_temp.data[0].name }} ansible_host={{ (web_droplet_temp.data[0].networks.v4[1].ip_address) }} beingprovisioned=true"
          when: droplet_type == "web" 


# LOADBALANCER
        - name: Get Private IP address of new Loadbalancer Droplet
          community.digitalocean.digital_ocean_droplet_info:
            oauth_token: "{{ lookup('ansible.builtin.env', 'DO_API_TOKEN') }}"
            id: "{{ lb_droplet_create_temp.data.droplet.id }}"
          register: droplet_temp
          when: droplet_type == "loadbalancer"

        - name: Add the new Loadbalancer Droplet to the inventory file
          become: true
          ansible.builtin.lineinfile:
            path=/etc/ansible/hosts
            state=present
            insertafter="\[loadbalancers\]"
            line="{{ lb_droplet_temp.data[0].name }} ansible_host={{  (lb_droplet_temp.data[0].networks.v4[1].ip_address) }}"
          when: droplet_type == "loadbalancer"  

        - name: Add the new Loadbalancer Droplet to the inventory file again for provisioning
          become: true
          ansible.builtin.lineinfile:
            path=/etc/ansible/hosts
            state=present
            insertafter="\[provisioning\]"
            line="{{ lb_droplet_temp.data[0].name }} ansible_host={{ (lb_droplet_temp.data[0].networks.v4[1].ip_address) }} beingprovisioned=true"
          when: droplet_type == "loadbalancer"           


#Only add host to role groups in inventory file when provisioning is complete, move these tasks around to ensure this happens



##### PROVISIONING #####

#Refresh Inventory File to pick up new host
        - name: Refresh Inventory File
          meta: refresh_inventory


#Below commands happen on the servers we are provisioning

# Gather facts must be set to no to prevent ansible from trying to connect to new droplet over ssh before its ready
- name: Bring Droplet up to baseline
  hosts: provisioning
  gather_facts: no
  vars:
    ansible_ssh_private_key_file: ~/.ssh/doinit
    ansible_ssh_user: root
  roles:
    - ubuntu20    

# This is seperate from above because we need the gathered facts here. By now the droplet is up and running and we can safely grab them
- name: Connect new Droplet to monitoring system 
  hosts: provisioning
  gather_facts: yes
  roles:
    - zabbix_agent    


#Figure out task to delete provisioning entries in inv file

##### INTEGRATION #####

# Integrate it into the existing infrastructure
- name: Configure and deploy the web tier
  hosts: webservers
  become: true
  become_user: root            
  roles:
    - nfs_client
    - nginx


- name: Configure and deploy the balance tier
  hosts: loadbalancers
  become: true
  vars:
    backends: "{{ groups['webservers'] }}"
  roles:
    - haproxy