---
- hosts: localhost
  vars_prompt:
    - name: droplet_type
      prompt: "What type of Droplet would you like to create? Choices: loadbalancer | web | wpadmin | control | file | base (Type exactly as seen here)"
      private: no

- name: Creation
  ansible.builtin.import_playbook: Creation/{{ droplet_type }}.yml

##### INTEGRATION #####

- name: Integration
  ansible.builtin.import_playbook: deploy.yml