---
- hosts: localhost
  vars_prompt:
    - name: droplet_type
      prompt: "What type of Droplet would you like to create? Choices: web (Type exactly as seen here)"
      private: no
  tasks: 
# Test Initial Provision using specific key
        - name: Genrate Random Number for Droplet name
          set_fact:
            num: "{{99 | random(start=11) }}"

        - name: Create a new Web Droplet
          community.digitalocean.digital_ocean_droplet:
            state: present
            oauth_token: "{{ lookup('ansible.builtin.env', 'DO_API_TOKEN') }}"
            name: Bene-NYC-Web{{ num }}v
            size: s-1vcpu-1gb-amd
            region: nyc3
            tags: bene, web
            image: ubuntu-20-04-x64
            project: Bene IT Websites
            wait_timeout: 500
            ssh_keys: [ a6:84:ee:f8:05:03:7d:24:09:d2:68:84:8e:d3:72:49 ]
          register: droplet_create_temp
          when: droplet_type == "web" 

# Droplet Creation commnad does not pass IP addresses, using seperate task to grab IP address

        - name: Get Private IP address of new Droplet
          community.digitalocean.digital_ocean_droplet_info:
            oauth_token: "{{ lookup('ansible.builtin.env', 'DO_API_TOKEN') }}"
            id: "{{ droplet_create_temp.data.droplet.id }}"
          register: droplet_temp

        - name: Add the new Web Droplet to the inventory file
          become: true
          ansible.builtin.lineinfile:
            path=/etc/ansible/hosts
            state=present
            insertafter="\[Web\]"
            line="{{ droplet_temp.data[0].name }} ansible_host={{  (droplet_temp.data[0].networks.v4[1].ip_address) }}"
          when: droplet_type == "web" 

#Refresh Inventory File to pick up new host

        - meta: refresh_inventory


# Bring new host up to baseline state

- name: Run Baseline 
  hosts: provisioning
  become: true
  become_user: root
  vars:
    ansible_ssh_private_key_file: ~/.ssh/doinit
    ansible_ssh_user: root
  roles:
    - ubuntu20

# Integrate it into the existing infrastructure
- name: Configure and deploy the web tier
  hosts: webservers
  become: true
  roles:
    - nfs_client
    - nginx
when: droplet_type == "web" 
    
- name: Configure and deploy the balance tier
  hosts: loadbalancers
  become: true
  vars:
    backends: "{{ groups['webservers'] }}"
  roles:
    - haproxy
 when: droplet_type == "web" or droplet_type == "loadbalancer"        