#########################################################
# Create New Wordpress Site
#########################################################
---
- hosts: BeneNYCDB01v:BeneNYCWeb01v
  become: true


    # DB Config
- hosts: BeneNYCDB01v
  vars_prompt:
    - name: sqluser
      prompt: Please provide an SQL username
      private: no

    - name: sqlpass
      prompt: Please Provide an SQL Password   

    - name: sqlname
      prompt: Please provide an SQL database name
      private: no
  tasks: 
        - name: Create a new database for website'
          community.mysql.mysql_db:
            name: "{{ sqlname }}"
            state: present 

        - name: Create database user and great access to database
          community.mysql.mysql_user:
            name: "{{ sqluser }}"
            password: "{{ sqlpass }}"
            priv: '{{ sqlname }}.*:ALL'
            state: present       

        - name: "Add SQL info to dummy host for use later in this playbook"
          add_host:
            name:   "SQLINFOHOLDER"
            sqluser:  "{{ sqluser }}"
            sqlpass:   "{{ sqlpass }}"
            sqlname:   "{{ sqlname }}"            


    # Nginx Config
- hosts: BeneNYCWeb01v
  vars_prompt:

    - name: domain
      prompt: What is the domain of the website
      private: no

    - name: domain2
      prompt: Is there a second domain for the website, like www.domain.com | Leave blank if no
      private: no   
  tasks: 
          - name: Create site directory if missing
            become: yes
            become_user: root  
            ansible.builtin.file:
              path: /mnt/Web/Websites/{{ domain }}
              state: directory

          - name: Download and extract wordpress files
            become: yes
            become_user: root          
            ansible.builtin.unarchive:
              src: https://wordpress.org/latest.tar.gz
              dest: /mnt/Web/Websites/{{ domain }}/
              remote_src: yes    

          - name: Move wordpress files to public directory
            become: yes
            become_user: root   
            command: mv /mnt/Web/Websites/{{ domain }}/wordpress /mnt/Web/Websites/{{ domain }}/public_html

          - name: Add custom WP-Config
            become: yes
            become_user: root             
            template: src=templates/wp-config.php 
                        dest=/mnt/Web/Websites/{{ domain }}/public_html/wp-config.php 
                        backup=no                

          - name: Add Nginx vhost for website
            become: yes
            become_user: root             
            template: src=templates/wpnginxvhost 
                        dest=/mnt/Web/VHosts/{{ domain }} 
                        backup=no


    # Cleanup
          - name: Set permissions on directory
            become: yes
            become_user: root            
            ansible.builtin.file:
              path: /mnt/Web/Websites/{{ domain }}
              state: directory
              owner: www-data
              group: www-data

          - name: Reload Nginx to pick up the new website
            ansible.builtin.systemd: 
              name: nginx
              state: reloaded
