#########################################################
# Create New Wordpress Site
#########################################################
---
- hosts: all
  become: true
  vars_files:
    - vars/default.yml

  tasks: