---
# Test Initial Provision using specific key

- name: Run Baseline 
  hosts: testing
  become: true
  become_user: root
  vars:
    ansible_ssh_private_key_file: ~/.ssh/doinit
    ansible_ssh_user: root
  roles:
    - ubuntu20    