#################################################
# reload web nodes
# requires ansible.posix from galaxy , install with
# ansible-galaxy collection install ansible.posix
#################################################
---
    - hosts: webservers
      become: true
      vars_files:
        - group_vars/webservers.yml

    # This shouldnt be needed but if its not here the playbook doesnt run, i have no idea
      tasks:
        - name: Install Prerequisites
          apt: name=aptitude update_cache=yes state=latest force_apt_get=yes


        - name: Reload Nginx and make sure it starts at boot
          ansible.builtin.systemd: 
            name: nginx
            enabled: yes
            state: reloaded