---
# This playbook deploys the entire web hosting stack


- name: Run updates and apply baseline configuration to all servers
  hosts: all
  become: true
  roles:
  - ubuntu20

- name: Configure and deploy the master database tier
  hosts: database_master
  become: true
  roles:
    - mariadb_master

- name: Configure and deploy the slave database tier
  hosts: database_slave
  become: true
  roles:
    - mariadb_slave

- name: Configure and deploy the storage tier
  hosts: storage
  become: true
  roles:
    - filestore

- name: Configure and deploy the web tier
  hosts: webservers
  become: true
  roles:
    - nfs_client
    - nginx

- name: Configure and deploy the balance tier
  hosts: loadbalancers
  become: true
  vars:
    backends: "{{ groups['webservers'] }}"
  roles:
    - haproxy