---
# This playbook deploys the entire web hosting stack

- name: Start of Job Monitoring
  hosts: localhost
  tasks:
    - name: Tell Healthchecks.io that we started the playbook
      ansible.builtin.uri:
        url: https://hc-ping.com/f80785ad-413d-4731-b0c9-79fc37b6f73b/start

- name: Configure and deploy the control tier
  hosts: command
  become: true
  roles:
    - nfs_client
    - control
    
- name: Configure and deploy the master database tier
  hosts: database_master
  become: true
  roles:
    - ubuntu20  
    - mariadb_master
    - zabbix_agent        

- name: Configure and deploy the slave database tier
  hosts: database_slave
  become: true
  roles:
    - ubuntu20  
    - mariadb_slave      
    - zabbix_agent   

- name: Configure and deploy the storage tier
  hosts: file
  become: true
  roles:
    - ubuntu20  
    - stefangweichinger.ansible_rclone
    - filestore    
    - zabbix_agent   

- name: Configure and deploy the web tier
  hosts: web
  become: true
  roles:
    - ubuntu22  
    - nfs_client
    - nginx 
    - zabbix_agent

- name: Configure and deploy the wp_admin tier
  hosts: wpadmin
  become: true
  roles:
    - ubuntu22      
    - nfs_client
    - wp_admin
    - zabbix_agent

- name: Deploy Wordpress Cron File to first WPAdmin host
  hosts: wpadmin[0]           
  become: true
  roles:
    - cron_wordpress

- name: Configure and deploy the balance tier
  hosts: loadbalancers
  become: true
  vars:
    webnodes: "{{ groups['web'] }}"
    wpanodes: "{{ groups['wpadmin'] }}"
  roles:
    - ubuntu22  
    - haproxy
    - zabbix_agent

- name: End of Job Monitoring
  hosts: localhost
  tasks:
    - name: Tell Healthchecks.io that we finished the playbook
      ansible.builtin.uri:
        url: https://hc-ping.com/f80785ad-413d-4731-b0c9-79fc37b6f73b
