---
# This playbook deploys the entire web hosting stack

- name: Configure and deploy the control tier
  hosts: control
  become: true
  roles:
    - nfs_client

- name: Configure and deploy the master database tier
  hosts: database_master
  become: true
  roles:
    - mariadb_master
    - ubuntu20
    - zabbix_agent        

- name: Configure and deploy the slave database tier
  hosts: database_slave
  become: true
  roles:
    - mariadb_slave
    - ubuntu20        
    - zabbix_agent   

- name: Configure and deploy the storage tier
  hosts: storage
  become: true
  roles:
    - filestore
    - ubuntu20    
    - zabbix_agent   

- name: Configure and deploy the web tier
  hosts: webservers
  become: true
  roles:
    - nfs_client
    - nginx
    - ubuntu20    
    - zabbix_agent

- name: Configure and deploy the wp_admin tier
  hosts: wp_admin
  become: true
  roles:
    - nfs_client
    - wp_admin
    - ubuntu20    
    - zabbix_agent       

- name: Configure and deploy the balance tier
  hosts: loadbalancers
  become: true
  vars:
    webnodes: "{{ groups['webservers'] }}"
    wpanodes: "{{ groups['wp_admin'] }}"
  roles:
    - haproxy
    - ubuntu20
    - zabbix_agent       