#########################################################
# Create New Wordpress Site
#########################################################
---
- hosts: localhost
  become: true
  vars_prompt:
    - name: sqluser
      prompt: Please provide an SQL username
      private: no

    - name: sqlpass
      prompt: Please Provide an SQL Password   

    - name: sqlname
      prompt: Please provide an SQL database name
      private: no


  tasks: 
        - name: Print the vars
          debug:
            msg: 1 {{ sqluser }} 2 {{ sqlpass }} 3 {{ sqlname }}


    