#################################################
# Storage config
#################################################
---
    - hosts: storage
      become: true
      vars_files:
        - group_vars/storage.yml


    # This shouldnt be needed but if its not here the playbook doesnt run, i have no idea
      tasks:
        - name: Install Prerequisites
          apt: name=aptitude update_cache=yes state=latest force_apt_get=yes

    # Install Packages
        - name: Update package mirrors and existing packages
          apt: update_cache=yes upgrade=yes
    
        - name: Install required system packages
          apt: name={{ sys_packages }} state=latest  

    # Mount the DO Volume
          - name: Mount the Web NFS Share
            ansible.posix.mount:
                src: /dev/disk/by-id/scsi-0DO_Volume_volume-nyc3-01
                path: /mnt/volume_nyc3_01
                opts: discard,defaults,noatime
                state: mounted
                fstype: ext4


    # Add Export for Nginx content
        - name: Add NFS export for nginx content
          become: yes
          become_user: root
          ansible.builtin.lineinfile:
            path: /etc/exports
            line: /mnt/volume_nyc3_01/Web/		10.132.0.0/24(rw,sync,no_root_squash,no_subtree_check)
            create: yes

    # Cleanup        
        - name: Reload the NFS Server and make sure it starts at boot
          ansible.builtin.systemd: 
            name: nfs-kernel-server
            enabled: yes
            state: reload