#################################################
# Storage config
# requires ansible.posix from galaxy , install with
# ansible-galaxy collection install ansible.posix
#################################################
---
    - hosts: storage
      become: true
      vars_files:
        - group_vars/storage.yml

      tasks:

    # Install Packages
        - name: Update package mirrors and existing packages
          apt: update_cache=yes upgrade=yes
    
        - name: Install required system packages
          apt: name={{ sys_packages }} state=latest  

        - name: Create Web directory if its missing
          ansible.builtin.file:
            path: /mnt/Web
            state: directory
            mode: '0755'


    # Add Export for Nginx content
        - name: Add NFS export for nginx content
          become: yes
          become_user: root
          ansible.builtin.lineinfile:
            path: /etc/exports
            line: /mnt/Web/		10.123.0.0/24(rw,sync,no_root_squash,no_subtree_check)
            create: yes

    # Cleanup        
        - name: Reload the NFS Server and make sure it starts at boot
          ansible.builtin.systemd: 
            name: nfs-kernel-server
            enabled: yes
            state: reloaded