#########################################################
# test
#########################################################
---
- hosts: BeneNYCWeb03v
  tasks: 
          - name: Recursively find /tmp files older than 2 days
            find:
              paths: /mnt/Web/VHosts/
              
- name: Print return information from the previous task
  ansible.builtin.debug:
    var: result
    verbosity: 2
