#################################################
# Loadbalancers config
#################################################
---
    - hosts: all
      become: true

      tasks:
      - name: print info
        debug:
          msg: "Host full name is {{ inventory_hostname }}. Short name is {{ inventory_hostname_short }}"
