#########################################################
# test
# Need to register all vhosts to a var and then make sure a folder exists for each
#########################################################
---
- hosts: BeneNYCWeb03v
  tasks: 
          - name: Find all current live websites
            find:
              paths: /mnt/Web/VHosts/
            register: find_result

          - name: Create cache directories if missing
            become: yes
            become_user: root            
            file:
              state: present
              path: "/opt/Testing/{{ item }}"
              state: directory
            loop: "{{ find_result['files'] | map(attribute='path') | map('regex_replace','^.*/(.*)$','\\1') | list }}"

          - name: Set permissions on cache directorys
            become: yes
            become_user: root            
            ansible.builtin.file:
              path: /opt/Cache/
              state: directory
              owner: www-data
              group: www-data
              recurse: yes            
              
