#################################################
# Loadbalancers config
#################################################
---
    - hosts: all
      become: true

      tasks:
        - name: host
          debug: msg="{{ item }}"
          with_items:
             - "{{ groups['web'] }}"