---
- hosts: localhost
  vars_prompt:
    - name: droplet_type
      prompt: "What type of Droplet would you like to create? Choices: web | loadbalancer | wpadmin | base (Type exactly as seen here)"
      private: no
  tasks: 
  #Have to generate a random number to be used in server name
        - name: Genrate Random Number for Droplet name
          set_fact:
            num: "{{ 99 | random(start=11) }}"

##### CREATION #####

# WEB SERVER
        - name: Create a new Web Droplet
          community.digitalocean.digital_ocean_droplet:
            state: present
            oauth_token: "{{ lookup('ansible.builtin.env', 'DO_API_TOKEN') }}"
            name: Bene-NYC-Web{{ num }}v
            size: s-1vcpu-2gb-amd
            region: nyc3
            tags: 
              - "web"
              - "web_cluster"
              - "wc_backend"              
            image: ubuntu-20-04-x64
            project: Bene IT Websites
            wait_timeout: 500
            ssh_keys: [ a6:84:ee:f8:05:03:7d:24:09:d2:68:84:8e:d3:72:49 ]
          when: droplet_type == "web"             
          register: droplet_create_temp

        - name: Show Droplet info
          ansible.builtin.debug:
            msg: |
              {{ droplet_create_temp.data.droplet.id }}
