#########################################################
# test
# Need to register all vhosts to a var and then make sure a folder exists for each
#########################################################
---
- hosts: BeneNYCWeb03v
  tasks: 
          - name: Recursively find /tmp files older than 2 days
            find:
              paths: /mnt/Web/VHosts/

