---
- hosts: web
  become: true

  tasks: 
        - name: Test pulling numbers from hostname
          ansible.builtin.debug:
            msg: System {{ inventory_hostname | regex_replace('[^0-9]','') }}







