#################################################
# webserver config
# requires ansible.posix from galaxy , install with
# ansible-galaxy collection install ansible.posix
#################################################
---
    - hosts: webservers
      become: true
      vars_files:
        - group_vars/webservers.yml

    # This shouldnt be needed but if its not here the playbook doesnt run, i have no idea
      tasks:
        - name: Install Prerequisites
          apt: name=aptitude update_cache=yes state=latest force_apt_get=yes

    # Install Packages
        - name: Update package mirrors and existing packages
          apt: update_cache=yes upgrade=yes
    
        - name: Install required system packages
          apt: name={{ sys_packages }} state=latest


    # Mount the NFS Share for config files
        - name: Create Web directory if its missing
          ansible.builtin.file:
            path: /mnt/Web
            state: directory
            mode: '0755'

        - name: Mount the Web NFS Share
          ansible.posix.mount:
            src: "{{ hostvars[groups['storage'][0]].ansible_host }}:/mnt/volume_nyc3_01/Web"
            path: /mnt/Web
            opts: rw,sync,hard,intr
            state: mounted
            fstype: nfs


    # Configure Nginx
        - name: Remove default Nginx config
          ansible.builtin.file:
            path: /etc/nginx/sites-enabled/default
            state: absent  

        - name: Update Nginx config
          template: src=templates/nginx.conf 
                      dest=/etc/nginx/nginx.conf 
                      backup=no


    # Configure PHP
        - name: Set max upload size for PHP
          become: yes
          become_user: root
          lineinfile:
           path: /etc/php/7.4/fpm/php.ini
           regexp: '{{item.From}}'
           line: '{{item.To}}'
           state: present  
          with_items:
              - { From: 'upload_max_filesize = 2M', To: 'upload_max_filesize = 15M' }
              - { From: 'post_max_size = 8M', To: 'post_max_size = 15M' }


    # Cleanup        
        - name: Reload Nginx and make sure it starts at boot
          ansible.builtin.systemd: 
            name: nginx
            enabled: yes
            state: reloaded

        - name: Restart PHP FPM and make sure it starts at boot
          ansible.builtin.service:
            name: php7.4-fpm
            enabled: yes
            state: restarted
