#################################################
# webserver config
# requires ansible.posix from galaxy , install with
# ansible-galaxy collection install ansible.posix
#################################################
---
    - hosts: all
      become: true
      vars_files:
        - group_vars/webservers.yml


    # This shouldnt be needed but if its not here the playbook doesnt run, i have no idea
      tasks:
        - name: Install Prerequisites
          apt: name=aptitude update_cache=yes state=latest force_apt_get=yes

    # Install Packages
        - name: Update package mirrors and existing packages
          apt: update_cache=yes upgrade=yes
    
        - name: Install required system packages
          apt: name={{ sys_packages }} state=latest


    # Mount the NFS Share for config files
        - name: Create Web directory if its missing
          ansible.builtin.file:
            path: /mnt/Web
            state: directory
            mode: '0755'

        - name: Mount the Web NFS Share
          ansible.posix.mount:
            src: {{ hostvars[store1].ansible_host }}:/mnt/volume_nyc3_01/Web
            path: /mnt/Web
            opts: rw,sync,hard,intr
            state: mounted
            fstype: nfs

