---
- name: Install required system packages
  apt: name={{ sys_packages }} state=present  

- name: Check if web directory has files
  stat: 
    path: /mnt/Web/data.txt
  register: nfs_share_data

- name: Create Web directory
  ansible.builtin.file:
    path: /mnt/Web
    state: directory
    mode: '0755'
  when: nfs_share_data.stat.exists == false

# rclone file backup
- name: Create rclone config directory if its missing
  become: yes
  become_user: root  
  ansible.builtin.file:
    path: /root/.config/rclone/
    state: directory
    mode: '0755'

- name: Place rclone config
  ansible.builtin.template:
    src: rclone.conf
    dest: /root/.config/rclone/rclone.conf
    trim_blocks: false
    backup=no

#Pull files from DO spaces if needed
- name: Pull files from DO spaces
  become: yes
  become_user: root
  shell: rclone copy Spaces:beneit/FileServerBackups /mnt/Web/
  when: nfs_share_data.stat.exists == false

# Add NFS Export for Nginx content
- name: Add NFS export for nginx content
  become: yes
  become_user: root
  ansible.builtin.lineinfile:
    path: /etc/exports
    line: /mnt/Web/		10.123.0.0/24(rw,async,no_root_squash,no_subtree_check)
    create: yes
  notify: restart nfs    


