---
- name: Install required system packages
  apt: name={{ sys_packages }} state=latest  

- name: Create Web directory if its missing
  ansible.builtin.file:
    path: /mnt/Web
    state: directory
    mode: '0755'

# rclone file backup

- name: Install rclone if not installed
  ansible.builtin.shell:
    cmd: files/install.sh
    creates: /usr/bin/rclone

- name: Create rclone config directory if its missing
  become: yes
  become_user: root  
  ansible.builtin.file:
    path: /home/ansible/.config/rclone/
    state: directory
    mode: '0755'

- name: Place rclone config
  ansible.builtin.copy:
    src: files/rclone.conf
    dest: /home/ansible/.config/rclone/rclone.conf
    remote_src: no



# Add NFS Export for Nginx content
- name: Add NFS export for nginx content
  become: yes
  become_user: root
  ansible.builtin.lineinfile:
    path: /etc/exports
    line: /mnt/Web/		10.123.0.0/24(rw,async,no_root_squash,no_subtree_check)
    create: yes
  notify: restart nfs    


