---
- hosts: localhost
  vars_prompt:
    - name: droplet_type
      prompt: "What type of Droplet would you like to create? Choices: loadbalancer | web | wpadmin | control | file | base (Type exactly as seen here)"
      private: no
  tasks: 
        - import_tasks: NewLoadbalancer.yml 
          when: droplet_type == "loadbalancer"
        - import_tasks: NewWeb.yml 
          when: droplet_type == "web"          