---
- hosts: localhost
  vars_prompt:
    - name: droplet_type
      prompt: "What type of Droplet would you like to create? Choices: loadbalancer | web | wpadmin | control | file | base (Type exactly as seen here)"
      private: no
  tasks: 
        - include_tasks: NewLoadbalancer.yml 
          when: droplet_type == "loadbalancer"
        - include_tasks: NewWeb.yml 
          when: droplet_type == "web"          

        - name: Print id
          ansible.builtin.debug:
            msg: System {{ droplet_create_temp.data.droplet.id }}          
####################
## PREPROVISIONING #
####################

        - name: Add provisioning tag to new droplet
          community.digitalocean.digital_ocean_tag:
            name: "provisioning"
            resource_id: "{{ droplet_create_temp.data.droplet.id }}"
            state: present

####################
### PROVISIONING ###
####################


# Gather facts must be set to no to prevent ansible from trying to connect to new droplet over ssh before its ready
- name: Bring Droplet up to baseline
  hosts: provisioning
  gather_facts: no
  vars:
    ansible_ssh_private_key_file: ~/.ssh/doinit
    ansible_ssh_user: root
  roles:
    - pro_ubuntu20

####################
# POSTPROVISIONING #
####################
- hosts: localhost
  tasks: 
        - name: Remove provisioning from the droplet
          community.digitalocean.digital_ocean_tag:
            name: "provisioning"
            resource_id: "{{ droplet_create_temp.data.droplet.id }}"
            state: absent