---
  #Have to generate a random number to be used in server name
        - name: Genrate Random Number for Droplet name
          set_fact:
            num: "{{ 99 | random(start=11) }}"

        - name: Create a new Control Droplet
          community.digitalocean.digital_ocean_droplet:
            state: present
            oauth_token: "{{ lookup('ansible.builtin.env', 'DO_API_TOKEN') }}"
            name: Bene-NYC-CC{{ num }}v
            size: s-1vcpu-2gb-amd
            region: nyc3
            tags: 
              - "command"
              - "web_cluster"
            image: ubuntu-20-04-x64
            project: Bene IT Websites
            wait_timeout: 500
            ssh_keys: [ a6:84:ee:f8:05:03:7d:24:09:d2:68:84:8e:d3:72:49 ] 
          register: droplet_create_temp    
