#################################################
# Basseline for ubuntu20 hosts
#################################################
---
#Newly created droplets might take a minute or two to respond to ssh
  - name: Wait for droplet to become reachable
    wait_for_connection:
      delay: 5
      sleep: 1
      timeout: 600

#Digital Ocean Monitoring causes APT locks during install when you create a droplet. the UNTIL option prevents that breaking the playbook
  - name: Install Package Manager Prerequisites
  apt: 
    name: aptitude 
    update_cache: yes 
    state: latest 
    force_apt_get: yes
  register: apt_status
  until: apt_status is success
  delay: 6
  retries: 10


- name: Update package mirrors and existing packages
  apt: update_cache=yes upgrade=yes
    
- name: Install required system packages
  apt: name={{ sys_packages }} state=latest

# Sudo Group Setup
- name: Make sure we have a 'bene' group
  group:
    name: bene
    state: present
    
- name: Allow 'bene' group to have passwordless sudo
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%bene'
    line: '%bene ALL=(ALL) NOPASSWD: ALL'
    validate: '/usr/sbin/visudo -cf %s'
    
# User + Key Setup
- name: Create a new regular user with sudo privileges
  user:
    name: "{{ create_user }}"
    state: present
    groups: bene
    append: true
    create_home: true
    shell: /bin/bash
    
- name: Set authorized key for remote user
  authorized_key:
    user: "{{ create_user }}"
    state: present
    key: "{{ copy_local_key }}"
    
# Upload SSH Config
- name: Upload custom ssh config
  copy:
    src: ubuntu20ssh.conf
    dest: /etc/ssh/sshd_config.d/benessh.conf
    remote_src: no
  notify: restart ssh server        

# MOTD Access Message
- name: Upload custom MOTD access warning
  copy:
    src: issue.net
    dest: /etc/issue.net
    remote_src: no
  notify: restart ssh server      

- name: Disable default banner message from MOTD
  become: yes
  become_user: root
  lineinfile:
    path: /etc/pam.d/sshd
    regexp: '{{item.From}}'
    line: '{{item.To}}'
    state: present  
  with_items:
      - { From: 'session    optional     pam_motd.so  motd=/run/motd.dynamic', To: '# session    optional     pam_motd.so  motd=/run/motd.dynamic' }
      - { From: 'session    optional     pam_motd.so noupdate', To: '# session    optional     pam_motd.so noupdate' }
  notify: restart ssh server        

# Fail2Ban Config
- name: Upload Fail2Ban config
  copy:
    src: jail.local
    dest: /etc/fail2ban/jail.local
    remote_src: no        
  notify: restart fail2ban       


# Zabbix Agent
- name: Download Zabbix deb file if missing
  get_url:
    url: "https://repo.zabbix.com/zabbix/5.2/ubuntu/pool/main/z/zabbix-release/zabbix-release_5.2-1%2Bubuntu20.04_all.deb"
    dest: "/tmp/zabbix.deb"

- name: Install Zabbix deb file
  become: true
  apt: deb="/tmp/zabbix.deb"

- name: install zabbix-agent2 v5.2 
  become: true
  apt:
    name: zabbix-agent2
    state: latest
    update_cache: yes
  notify: restart zabbix_agent       

- name: Place zabbix-agent config
  become: yes
  template:
    src=zabbix_agent2.conf 
    dest=/etc/zabbix/zabbix_agent2.conf 
    backup=no
  notify: restart zabbix_agent           
