#################################################
# Basseline for ubuntu20 hosts
#################################################
---
- name: Update package mirrors and existing packages
  apt: update_cache=yes upgrade=yes
    
# Sudo Group Setup
- name: Make sure we have a 'bene' group
  group:
    name: bene
    state: present
    
- name: Allow 'bene' group to have passwordless sudo
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%bene'
    line: '%bene ALL=(ALL) NOPASSWD: ALL'
    validate: '/usr/sbin/visudo -cf %s'
        
# Upload SSH Config
- name: Upload custom ssh config
  copy:
    src: ubuntu20ssh.conf
    dest: /etc/ssh/sshd_config.d/benessh.conf
    remote_src: no
  notify: restart ssh server           

# Fail2Ban Config
- name: Upload Fail2Ban config
  copy:
    src: jail.local
    dest: /etc/fail2ban/jail.local
    remote_src: no        
  notify: restart fail2ban