#################################################
# Basseline for ubuntu20 hosts
#################################################
---
- name: Install Prerequisites
  apt: name=aptitude update_cache=yes state=latest force_apt_get=yes
    
- name: Update package mirrors and existing packages
  apt: update_cache=yes upgrade=yes
    
- name: Install required system packages
  apt: name={{ sys_packages }} state=latest

# Sudo Group Setup
- name: Make sure we have a 'bene' group
  group:
    name: bene
    state: present
    
- name: Allow 'bene' group to have passwordless sudo
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%bene'
    line: '%bene ALL=(ALL) NOPASSWD: ALL'
    validate: '/usr/sbin/visudo -cf %s'
    
# User + Key Setup
- name: Create a new regular user with sudo privileges
  user:
    name: "{{ create_user }}"
    state: present
    groups: bene
    append: true
    create_home: true
    shell: /bin/bash
    
- name: Set authorized key for remote user
  authorized_key:
  user: "{{ create_user }}"
  state: present
  key: "{{ copy_local_key }}"
    
# Upload SSH Config
- name: Upload custom ssh config
  copy:
    src: files/SetupUbuntu2004/ubuntu20ssh.conf
    dest: /etc/ssh/sshd_config.d/benessh.conf
    remote_src: no
  notify: restart ssh server        

# MOTD Access Message
- name: Upload custom MOTD access warning
  copy:
    src: files/SetupUbuntu2004/issue.net
    dest: /etc/issue.net
    remote_src: no
  notify: restart ssh server      

- name: Disable default banner message from MOTD
  become: yes
  become_user: root
  lineinfile:
    path: /etc/pam.d/sshd
    regexp: '{{item.From}}'
    line: '{{item.To}}'
    state: present  
  with_items:
      - { From: 'session    optional     pam_motd.so  motd=/run/motd.dynamic', To: '# session    optional     pam_motd.so  motd=/run/motd.dynamic' }
      - { From: 'session    optional     pam_motd.so noupdate', To: '# session    optional     pam_motd.so noupdate' }
  notify: restart ssh server        

# Fail2Ban Config
- name: Upload Fail2Ban config
  copy:
    src: files/SetupUbuntu2004/jail.local
    dest: /etc/fail2ban/jail.local
    remote_src: no        
  notify: restart fail2ban       
