---
- name: Install required system packages
  apt: name={{ sys_packages }} state=latest

- name: Allow incoming connections on the master node
  become: yes
  become_user: root
  lineinfile:
    path: /etc/mysql/mariadb.conf.d/50-server.cnf
    regexp: 'bind-address            = 127.0.0.1'
    line: 'bind-address            = 0.0.0.0'
    state: present  

- name: Add files for other playbooks
  copy:
    src: .my.cnf
    dest: /home/ansible/.my.cnf
    remote_src: no

- name: Update master node config
  become: yes
  become_user: root
  blockinfile:
    path: /etc/mysql/mariadb.conf.d/50-server.cnf
    block: |
      server-id = 1
      log_bin = /var/log/mysql/mysql-bin.log
      log_bin_index =/var/log/mysql/mysql-bin.log.index
      relay_log = /var/log/mysql/mysql-relay-bin' 
      relay_log_index = /var/log/mysql/mysql-relay-bin.index
