---
- hosts: webservers
  become: true
  vars_prompt:
    - name: domain
      prompt: Please provide domain name of website cache to clear
      private: no

  tasks: 
        - name: Indexing Cache Files
          ansible.builtin.find:
            path: "/opt/Cache/{{ domain }}/"
          register: cleanup
          ignore_errors: true


        - name: Removing all files previously found in files dir
          ansible.builtin.file:
            path: "/opt/Cache/{{ domain }}/"
            state: absent
          with_items: "{{ cleanup.files }}"
          ignore_errors: true
