# Syncs files from File server to digital ocean spaces for
# faster restore and replacement of node
# Using rlcone sync, it will empty DO space if files are missing
---
- hosts: storage[0]  
  tasks: 

#Check if files exist on NFS share, if they dont this playbook will wipe directory
        - name: Make sure we have files to backup
          ansible.builtin.stat:
            path: /mnt/Web/data.txt
          register: nfs_share_data

#Run backup using rclone sync
        - name: Sync files from cluster to DO Spaces
          become: true
          become_user: root
          shell: sudo rclone sync /mnt/Web/ Spaces:beneit/FileServerBackups --check-first --retries 1
          when: nfs_share_data.stat.exists == true
