#################################################
# reload web nodes
#################################################
---
    - hosts: web
      become: true
      tasks:
        - name: Reload Nginx and make sure it starts at boot
          ansible.builtin.systemd: 
            name: nginx
            enabled: yes
            state: reloaded

    - hosts: wpadmin
      become: true
      tasks:
        - name: Reload Nginx and make sure it starts at boot
          ansible.builtin.systemd: 
            name: nginx
            enabled: yes
            state: reloaded            