#################################################
# zabbix agent
#################################################
---
- name: Gather package facts
  package_facts:
    manager: "auto"

- name: show apache2 version
  debug: "{{ ansible_facts.packages['zabbix-agent2']
     | map(attribute='version')}}"
