#################################################
# zabbix agent
#################################################
---
- name: Gather package facts
  package_facts:
    manager: "auto"

- name: Print zabbix-agent2 version
  ansible.builtin.debug:
    msg: "{{ ansible_facts.packages['zabbix-agent2'][0]['version'] }}"

