#################################################
# zabbix agent
#################################################
---
tasks:
  - name: Gather package facts
    package_facts:
      manager: auto
    register: packages

  - set_fact:
      final_list: >
        {{ final_list | default([]) + [ item.name + "-" + item.version ] }}
    loop: "{{ packages | json_query('ansible_facts.packages.[*]') | flatten }}"

  - debug:
      var: final_list