#################################################
# zabbix agent
#################################################
---
- name: Gather package facts
  package_facts:
    manager: "auto"


- name: Print zabbix-agent2 version
  ansible.builtin.debug:
    msg: "{{ ansible_facts.packages['zabbix-agent2'][0]['version'] }}"

- name: Download Zabbix deb file
  get_url:
    url: "https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-4%2Bubuntu20.04_all.deb"
    dest: "/tmp/zabbix.deb"
  when: ansible_facts.packages.['zabbix_agent2'][0].version is match("1:6.0.14-1+ubuntu20.04")

- name: Install Zabbix deb file
  become: true
  apt: deb="/tmp/zabbix.deb"

- name: install zabbix-agent2 v6 
  become: true
  apt:
    name: zabbix-agent2
    state: latest
    update_cache: yes
  notify: restart zabbix_agent       

- name: Place zabbix-agent config
  become: yes
  template:
    src=zabbix_agent2.conf 
    dest=/etc/zabbix/zabbix_agent2.conf 
    backup=no
  notify: restart zabbix_agent     
