#################################################
# zabbix agent
#################################################
---
- name: Gather package facts
  package_facts:
    manager: "auto"

- name: Check whether a package called foobar is installed
  ansible.builtin.debug:
    msg: "{{ ansible_facts.packages['zabbix-agent2'.version] | length }} versions of foobar are installed!"
