#################################################
# zabbix agent
#################################################
---
- name: Gather package facts
  package_facts:
    manager: "auto"

- name: show apache2 version
  debug: var=ansible_facts.packages.zabbix_agent2[0].version

- name: Print the package facts
  ansible.builtin.debug:
    var: ansible_facts.packages
