#################################################
# zabbix agent
#################################################
---
- name: Download Zabbix deb file if missing
  get_url:
    url: "https://repo.zabbix.com/zabbix/5.2/ubuntu/pool/main/z/zabbix-release/zabbix-release_5.2-1%2Bubuntu20.04_all.deb"
    dest: "/tmp/zabbix.deb"

- name: Install Zabbix deb file
  become: true
  apt: deb="/tmp/zabbix.deb"

- name: install zabbix-agent2 v5.2 
  become: true
  apt:
    name: zabbix-agent2
    state: latest
    update_cache: yes
  notify: restart zabbix_agent       

- name: Place zabbix-agent config
  become: yes
  template:
    src=zabbix_agent2.conf 
    dest=/etc/zabbix/zabbix_agent2.conf 
    backup=no
  notify: restart zabbix_agent     

#Make ansible wait for zabbix to start for first time before running handler, sometimes handler will run before zabbix service file is there. 
- name: Wait for Zabbix Agent to start
  service:
    name: zabbix-agent2 
    state: started
  register: zabbixstatus
  until: zabbixstatus.status.ActiveState == "active"
  retries: 10
  delay: 10

- name: Print contents of var we are saving 
  ansible.builtin.debug:
    msg: System {{ zabbixstatus }} 