---
- name: Install required system packages
  apt: name={{ sys_packages }} state=present

- name: Allow incoming connections on the slave node
  become: yes
  become_user: root
  lineinfile:
    path: /etc/mysql/mariadb.conf.d/50-server.cnf
    regexp: 'bind-address            = 127.0.0.1'
    line: 'bind-address            = 0.0.0.0'
    state: present  

- name: Update slave node config
  become: yes
  become_user: root        
  blockinfile:
    path: /etc/mysql/mariadb.conf.d/50-server.cnf
    block: |
      server-id = 2
      log_bin = /var/log/mysql/mysql-bin.log
      log_bin_index =/var/log/mysql/mysql-bin.log.index
      relay_log = /var/log/mysql/mysql-relay-bin' 
      relay_log_index = /var/log/mysql/mysql-relay-bin.index
